### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ardimasp** [edeliciouso/FSM-Air-Conditioner#1]
I got an error when I tried to compile your code. Also, I don't think you call the function in the mylib.c in your main.c. 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/5621601/212732543-ae799cd5-6bb2-4c29-814a-0d7710ab47c6.png">

**Comment by edeliciouso** [comment]
I think I've fixed the issues sir. Thank you.
